apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: movie-trailers
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://postgres:5432/movie_trailers
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.generate-ddl=true
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.open-in-view=false
    spring.thymeleaf.cache=false
    spring.servlet.multipart.max-file-size=100MB
    storage.location=assets
    spring.docker.compose.enabled=false